name: Oceanography
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.7
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray>=0.11.3
  - cartopy
  - esmpy
  - intake-xarray
  - geopy
  - xesmf
  - xgcm>=0.2.0
  - Ipython
  - tqdm
  - pytest
  - pytest-cov
  - pytest-env
  - codecov
  - pycodestyle
  - ipython
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - cmocean
  - eofs
  - gsw
  - pycwt
  - seaborn
  - pyviz
  - jupyterlab
  - nodejs 
  - ffmpeg
  - oceanspy=
  - xhistogram
  - ffmpeg
  - xmitgcm>=0.3.0
